{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cctensor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ccTensor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ccTensor/ccTensor_{{ version }}.tar.gz
  sha256: 76617f8118b002b56265da397b50161a50f2703539c85de6020f30ad76c162fd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.1
    - r-mass
    - r-fields
    - r-igraph
    - r-rtensor
  run:
    - r-base >=4.1
    - r-mass
    - r-fields
    - r-igraph
    - r-rtensor

test:
  commands:
    - $R -e "library('ccTensor')"           # [not win]
    - "\"%R%\" -e \"library('ccTensor')\""  # [win]

about:
  home: https://github.com/rikenbit/ccTensor
  license: Artistic-2.0
  summary: CUR/CX decomposition factorizes a matrix into two factor matrices and Multidimensional CX Decomposition factorizes a tensor into a core tensor and some factor matrices. See the reference section of GitHub README.md <https://github.com/rikenbit/ccTensor>, for details of the methods.
  license_family: OTHER
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ccTensor
# Type: Package
# Title: CUR/CX Tensor Decomposition
# Version: 1.0.2
# Date: 2021-08-02
# Authors@R: c(person("Koki", "Tsuyuzaki", role = c("aut", "cre"), email = "k.t.the-answer@hotmail.co.jp"), person("Itoshi", "Nikaido", role = "aut"))
# Depends: R (>= 4.1.0)
# Imports: methods, fields, MASS, igraph, rTensor
# Suggests: testthat, nnTensor
# Description: CUR/CX decomposition factorizes a matrix into two factor matrices and Multidimensional CX Decomposition factorizes a tensor into a core tensor and some factor matrices. See the reference section of GitHub README.md <https://github.com/rikenbit/ccTensor>, for details of the methods.
# License: Artistic-2.0
# URL: https://github.com/rikenbit/ccTensor
# NeedsCompilation: no
# Packaged: 2021-08-11 23:40:36 UTC; root
# Author: Koki Tsuyuzaki [aut, cre], Itoshi Nikaido [aut]
# Maintainer: Koki Tsuyuzaki <k.t.the-answer@hotmail.co.jp>
# Repository: CRAN
# Date/Publication: 2021-08-12 04:30:07 UTC
